<?php

return array (
  0 => 
  array (
    'type' => 'file',
    'name' => 'discover',
    'title' => '发现种草',
    'icon' => 'fa fa-list',
    'url' => '',
    'condition' => '',
    'remark' => '',
    'ismenu' => 1,
    'menutype' => 'addtabs',
    'extend' => '',
    'py' => 'fxzc',
    'pinyin' => 'faxianzhongcao',
    'weigh' => 999,
    'sublist' => 
    array (
      0 => 
      array (
        'type' => 'file',
        'name' => 'discover/content',
        'title' => '内容中心',
        'icon' => 'fa fa-folder-open',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'nrzx',
        'pinyin' => 'neirongzhongxin',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'discover/review',
            'title' => '帖子审核',
            'icon' => 'fa fa-check-square-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tzsh',
            'pinyin' => 'tiezishenhe',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'discover/review/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'discover/review/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'discover/review/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'discover/discover',
            'title' => '帖子管理',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'fxdt',
            'pinyin' => 'faxiandongtai',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'discover/discover/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'discover/discover/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'discover/discover/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'discover/discover/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'discover/discover/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'discover/discover/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'discover/comment',
            'title' => '评论管理',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'fxpl',
            'pinyin' => 'faxianpinglun',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'discover/comment/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'discover/comment/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'discover/comment/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'discover/comment/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'discover/comment/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'discover/comment/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'discover/tag',
            'title' => '标签管理',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'fxbq',
            'pinyin' => 'faxianbiaoqian',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'discover/tag/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'discover/tag/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'discover/tag/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'discover/tag/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'discover/tag/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'discover/tag/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'discover/topic',
            'title' => '话题管理',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'fxht',
            'pinyin' => 'faxianhuati',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'discover/topic/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'discover/topic/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'discover/topic/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'discover/topic/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'discover/topic/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'discover/topic/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
        ),
      ),
      1 => 
      array (
        'type' => 'file',
        'name' => 'discover/schoolops',
        'title' => '学校运营',
        'icon' => 'fa fa-university',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'xxyy',
        'pinyin' => 'xuexiaoyunying',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'discover/school',
            'title' => '学校管理',
            'icon' => 'fa fa-university',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'xxgl',
            'pinyin' => 'xuexiaoguanli',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'discover/school/import',
                'title' => '导入',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'dr',
                'pinyin' => 'daoru',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'discover/school/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'discover/school/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'discover/school/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'discover/school/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              5 => 
              array (
                'type' => 'file',
                'name' => 'discover/school/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
        ),
      ),
      2 => 
      array (
        'type' => 'file',
        'name' => 'discover/attentions',
        'title' => '发现-关注',
        'icon' => 'fa fa-circle-o',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'fxgz',
        'pinyin' => 'faxianguanzhu',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'discover/attentions/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'discover/attentions/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'discover/attentions/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'discover/attentions/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'discover/attentions/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'discover/attentions/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      3 => 
      array (
        'type' => 'file',
        'name' => 'discover/collect',
        'title' => '发现-收藏',
        'icon' => 'fa fa-circle-o',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'fxsc',
        'pinyin' => 'faxianshoucang',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'discover/collect/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'discover/collect/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'discover/collect/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'discover/collect/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'discover/collect/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'discover/collect/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      4 => 
      array (
        'type' => 'file',
        'name' => 'discover/favor',
        'title' => '发现-点赞',
        'icon' => 'fa fa-circle-o',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'fxdz',
        'pinyin' => 'faxiandianzan',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'discover/favor/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'discover/favor/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'discover/favor/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'discover/favor/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'discover/favor/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'discover/favor/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      5 => 
      array (
        'type' => 'file',
        'name' => 'discover/log',
        'title' => '发现-消息提醒',
        'icon' => 'fa fa-circle-o',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'fxxxtx',
        'pinyin' => 'faxianxiaoxitixing',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'discover/log/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'discover/log/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'discover/log/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'discover/log/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'discover/log/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'discover/log/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      6 => 
      array (
        'type' => 'file',
        'name' => 'discover/operation',
        'title' => '运营中心',
        'icon' => 'fa fa-bullhorn',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'py' => 'yyzx',
        'pinyin' => 'yunyingzhongxin',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'discover/group_qrcode',
            'title' => '群二维码',
            'icon' => 'fa fa-qrcode',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'qewm',
            'pinyin' => 'qunerweima',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'discover/group_qrcode/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'discover/group_qrcode/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'discover/group_qrcode/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'discover/group_qrcode/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'discover/group_qrcode/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'discover/home_banner',
            'title' => '首页广告位',
            'icon' => 'fa fa-image',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 1,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'syggw',
            'pinyin' => 'shouyeguanggaowei',
            'weigh' => 0,
            'sublist' => 
            array (
              0 => 
              array (
                'type' => 'file',
                'name' => 'discover/home_banner/index',
                'title' => '查看',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'zk',
                'pinyin' => 'zhakan',
                'weigh' => 0,
              ),
              1 => 
              array (
                'type' => 'file',
                'name' => 'discover/home_banner/add',
                'title' => '添加',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'tj',
                'pinyin' => 'tianjia',
                'weigh' => 0,
              ),
              2 => 
              array (
                'type' => 'file',
                'name' => 'discover/home_banner/edit',
                'title' => '编辑',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'bj',
                'pinyin' => 'bianji',
                'weigh' => 0,
              ),
              3 => 
              array (
                'type' => 'file',
                'name' => 'discover/home_banner/del',
                'title' => '删除',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'sc',
                'pinyin' => 'shanchu',
                'weigh' => 0,
              ),
              4 => 
              array (
                'type' => 'file',
                'name' => 'discover/home_banner/multi',
                'title' => '批量更新',
                'icon' => 'fa fa-circle-o',
                'url' => '',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'menutype' => NULL,
                'extend' => '',
                'py' => 'plgx',
                'pinyin' => 'pilianggengxin',
                'weigh' => 0,
              ),
            ),
          ),
        ),
      ),
    ),
  ),
);
